### ISSUE TITLE
Bug report test label

### ISSUE THREAD

**Issue by gaetansenn** [cmty/test#110]
### Version

[0.0.1](https://github.com/cmty/test/releases/tag/0.0.1)

### Reproduction link

[cmty.io](cmty.io)

### Steps to reproduce

Go to issues listing

### What is expected ?

get good label state

### What is actually happening?

Nothing...

**Comment by benjamincanac** [comment]
@Atinux Tu en penses quoi ?

**Comment by Atinux** [comment]
Non je pense que c'est bon, le label est bien ajouté.

**Comment by benjamincanac** [comment]
cdzfdz
