### ISSUE TITLE
Check label state

### ISSUE THREAD

**Issue by gaetansenn** [cmty/test#113]
### Version

[0.0.1](https://github.com/cmty/test/releases/tag/0.0.1)

### Reproduction link

[cmty.io](cmty.io)

### Steps to reproduce

go to issues listing

### What is expected ?

get good badge

### What is actually happening?

Having done label state

<div align="right"><sub><em>This bug report is available on <a href="http://terrjas.cmty.localhost">Terra JS</a> community (<a href="http://terrjas.cmty.localhost/cmty/test/issues/c60">#c60</a>)</em></sub></div>

**Comment by benjamincanac** [comment]
test

**Comment by benjamincanac** [comment]
toto

**Comment by benjamincanac** [comment]
tata

**Comment by benjamincanac** [comment]
titi

**Comment by benjamincanac** [comment]
fff

**Comment by benjamincanac** [comment]
hihi

**Comment by benjamincanac** [comment]
aaa

**Comment by benjamincanac** [comment]
bbb

**Comment by benjamincanac** [comment]
ccc

**Comment by benjamincanac** [comment]
ddd

**Comment by benjamincanac** [comment]
test
